### ISSUE TITLE
reviewing master javascript layout

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#521] opened 2021-11-08 18:08 UTC

**Comment by tommygonzaleza** [comment] 2021-11-26 15:57
Hello! @ElviraQDP Can you please describe this issue better, I'm not sure what the problem is. Thanks!

**Comment by ElviraQDP** [comment] 2021-11-27 15:41
I'm checking the layout of the exercises, checking for the correct markdown on the README's

**Comment by tommygonzaleza** [comment] 2022-01-11 16:52
I don't see any PR, but I'm going to close this issue as we are going to review all the exercises markdown syntax when we apply the new structure that we created.

**Closed by tommygonzaleza** 2022-01-11 16:52 UTC
